version: '3.8'
services:
  db:
    build:
      context: .
      dockerfile:
        db.Dockerfile
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: sample
    ports:
      - 3306:3306
    tty: true
    volumes:
      - .:/app:cached
  api:
    build:
      context: .
      dockerfile: api.Dockerfile
      target: development
    ports:
      - 8080:8080
    volumes:
      - .:/app:cached
    tty: true
    env_file:
      - ./docker-compose.env
    environment:
      APP_ENV: development
      DB_USER: root
      DB_PASS: password
      DB_HOST: db
      DB_NAME: sample
      DB_PORT: 3306
    links:
      - db
  batch:
    build:
      context: .
      dockerfile: batch.Dockerfile
    volumes:
      - .:/app:cached
    tty: true
    environment:
      APP_ENV: development
      DB_USER: root
      DB_PASS: password
      DB_HOST: db
      DB_NAME: sample
      DB_PORT: 3306
    links:
      - db
