CREATE TABLE IF NOT EXISTS users (
    `id` BIGINT UNSIGNED NOT NULL,
    `auth0_uid` VARCHAR(100) NOT NULL,
    `first_name` VARCHAR(100) NOT NULL,
    `last_name` VARCHAR(100) NOT NULL,
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY `auth0_uid` (`auth0_uid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;