// Code generated by ent, DO NOT EDIT.

package ent

import (
	"sample-server/ent/schema"
	"sample-server/ent/user"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescAuth0UID is the schema descriptor for auth0_uid field.
	userDescAuth0UID := userFields[1].Descriptor()
	// user.Auth0UIDValidator is a validator for the "auth0_uid" field. It is called by the builders before save.
	user.Auth0UIDValidator = userDescAuth0UID.Validators[0].(func(string) error)
	// userDescFirstName is the schema descriptor for first_name field.
	userDescFirstName := userFields[2].Descriptor()
	// user.FirstNameValidator is a validator for the "first_name" field. It is called by the builders before save.
	user.FirstNameValidator = userDescFirstName.Validators[0].(func(string) error)
	// userDescLastName is the schema descriptor for last_name field.
	userDescLastName := userFields[3].Descriptor()
	// user.LastNameValidator is a validator for the "last_name" field. It is called by the builders before save.
	user.LastNameValidator = userDescLastName.Validators[0].(func(string) error)
}
